/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passportmanagementsystem;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nitheesh
 */
public class ApplicationDetailsJFrame extends Applicant {
    
    private boolean[] validFields;
    protected int appID;
    private String dobString;
    private Profile p;
    
    /**
     * Creates new form ApplicationDetailsJFrame
     */
    public ApplicationDetailsJFrame() {
        initComponents();
        validFields = new boolean[6];
        p = new Profile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fNameTxtField = new javax.swing.JTextField();
        nameTxtField = new javax.swing.JTextField();
        dobTxtField = new javax.swing.JTextField();
        panTxtField = new javax.swing.JTextField();
        nativeTxtField = new javax.swing.JTextField();
        aadharTxtField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create new application");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Application Form");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Father's Name:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Date of Birth:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Native:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("PAN:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Aadhar Number:");

        fNameTxtField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        fNameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNameTxtFieldFocusLost(evt);
            }
        });

        nameTxtField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        nameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFieldFocusLost(evt);
            }
        });

        dobTxtField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        dobTxtField.setToolTipText("DD-MM-YYYY");
        dobTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dobTxtFieldFocusLost(evt);
            }
        });

        panTxtField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        panTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                panTxtFieldFocusLost(evt);
            }
        });

        nativeTxtField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        nativeTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nativeTxtFieldFocusLost(evt);
            }
        });

        aadharTxtField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        aadharTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                aadharTxtFieldFocusLost(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(dobTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(panTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(nativeTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(aadharTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(nameTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dobTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nativeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aadharTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean allValidFields() {
        return (validFields[0] && validFields[1] && validFields[2] &&
                validFields[3] && validFields[4] && validFields[5]);
    }
    
    public String getName() {
        return nameTxtField.getText().trim();
    }
    
    public String getDob() {
        return dobTxtField.getText().trim();
    }
    
    public String getFathersName() {
        return fNameTxtField.getText().trim();
    }
    
    public String getNative() {
        return nativeTxtField.getText().trim();
    }
    
    public String getAadharNo() {
        return aadharTxtField.getText().trim();
    }
    
    public String getPan() {
        return panTxtField.getText().trim();
    }
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        name = getName();
        dobString = getDob();
        fathersName = getFathersName();
        Native = getNative();
        aadharNo = Long.parseLong(getAadharNo());
        String pan = getPan();
        appID = p.register(name,dobString,fathersName,Native,aadharNo,pan);
        if (appID != -1) {
            JOptionPane.showMessageDialog(null, "Application created! Your "
            + "application ID is " + appID);
            new ApplicationUI().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null,"There was a problem creating"
                + "the application. Try again.");
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void nameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFieldFocusLost
        String name = getName();
        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter name");
            validFields[0] = false;
        } else {
            validFields[0] = true;
        }
        submitButton.setEnabled(allValidFields());
    }//GEN-LAST:event_nameTxtFieldFocusLost

    private void dobTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobTxtFieldFocusLost
        String dobString = getDob();
        validFields[1] = true;
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date myDate;
        try {
            myDate = formatter.parse(dobString);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Please enter a proper date");
            validFields[1] = false;
        }
        submitButton.setEnabled(allValidFields());
    }//GEN-LAST:event_dobTxtFieldFocusLost

    private void fNameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameTxtFieldFocusLost
        String fName = getFathersName();
        if(fName.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter father's name");
            validFields[2] = false;
        } else {
            validFields[2] = true;
        }
        submitButton.setEnabled(allValidFields());
    }//GEN-LAST:event_fNameTxtFieldFocusLost

    private void nativeTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nativeTxtFieldFocusLost
        String Native = getNative();
        if(Native.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter native");
            validFields[3] = false;
        } else {
            validFields[3] = true;
        }
        submitButton.setEnabled(allValidFields());
    }//GEN-LAST:event_nativeTxtFieldFocusLost

    private void aadharTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aadharTxtFieldFocusLost
        String aadharNo = getAadharNo();
        if(aadharNo.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter aadhar number");
            validFields[4] = false;
        } else {
            if(aadharNo.matches(".*[a-zA-Z].*")){
                JOptionPane.showMessageDialog(null, "Please enter a valid "
                    + "Aadhar number");
            }
            validFields[4] = !aadharNo.matches(".*[a-zA-Z].*");
        }
        submitButton.setEnabled(allValidFields());
    }//GEN-LAST:event_aadharTxtFieldFocusLost

    private void panTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panTxtFieldFocusLost
        String pan = getPan();
        if(pan.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter PAN");
            validFields[5] = false;
        } else {
            validFields[5] = true;
        }
        submitButton.setEnabled(allValidFields());
    }//GEN-LAST:event_panTxtFieldFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new ApplicationUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationDetailsJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadharTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dobTxtField;
    private javax.swing.JTextField fNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField nativeTxtField;
    private javax.swing.JTextField panTxtField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
